export const RSS_FEEDS = [
  { url: 'https://feeds.feedburner.com/ndtvnews-top-stories', name: 'NDTV', category: 'india', region: 'india' },
  { url: 'https://www.thehindu.com/news/national/?service=rss', name: 'The Hindu', category: 'india', region: 'india' },
  { url: 'https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms', name: 'Times of India', category: 'india', region: 'india' },
  { url: 'https://indianexpress.com/section/india/feed/', name: 'Indian Express', category: 'india', region: 'india' },
  { url: 'https://scroll.in/feed', name: 'Scroll.in', category: 'india', region: 'india' },
  { url: 'https://thewire.in/feed', name: 'The Wire', category: 'india', region: 'india' },
  { url: 'https://www.livemint.com/rss/news', name: 'Livemint', category: 'india', region: 'india' },
  { url: 'https://www.deccanherald.com/rss/india.rss', name: 'Deccan Herald', category: 'india', region: 'india' },
  { url: 'https://theprint.in/feed/', name: 'The Print', category: 'india', region: 'india' },
  { url: 'https://www.news18.com/rss/india.xml', name: 'News18', category: 'india', region: 'india' },
  { url: 'https://www.firstpost.com/rss/india.xml', name: 'Firstpost', category: 'india', region: 'india' },
  { url: 'https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml', name: 'Hindustan Times', category: 'india', region: 'india' },
  { url: 'https://www.onmanorama.com/rss.xml', name: 'Onmanorama', category: 'india', region: 'kerala' },
  { url: 'https://www.thenewsminute.com/feed', name: 'The News Minute', category: 'india', region: 'kerala' },
  { url: 'https://gulfnews.com/rss', name: 'Gulf News', category: 'gcc', region: 'uae' },
  { url: 'https://www.khaleejtimes.com/rss', name: 'Khaleej Times', category: 'gcc', region: 'uae' },
  { url: 'https://www.arabnews.com/rss.xml', name: 'Arab News', category: 'gcc', region: 'saudi' },
  { url: 'https://www.aljazeera.com/xml/rss/all.xml', name: 'Al Jazeera', category: 'gcc', region: 'qatar' },
  { url: 'https://www.thenationalnews.com/rss', name: 'The National', category: 'gcc', region: 'uae' },
  { url: 'https://www.gulftoday.ae/rss', name: 'Gulf Today', category: 'gcc', region: 'uae' },
  { url: 'https://gulfbusiness.com/feed', name: 'Gulf Business', category: 'business', region: 'gcc' },
  { url: 'https://economictimes.indiatimes.com/rss.cms', name: 'Economic Times', category: 'business', region: 'india' },
  { url: 'https://www.business-standard.com/rss', name: 'Business Standard', category: 'business', region: 'india' },
  { url: 'https://www.financialexpress.com/feed/', name: 'Financial Express', category: 'business', region: 'india' },
  { url: 'https://techcrunch.com/feed/', name: 'TechCrunch', category: 'technology', region: 'global' },
  { url: 'https://www.theverge.com/rss/index.xml', name: 'The Verge', category: 'technology', region: 'global' },
  { url: 'https://yourstory.com/feed', name: 'YourStory', category: 'technology', region: 'india' },
  { url: 'https://inc42.com/feed/', name: 'Inc42', category: 'technology', region: 'india' },
  { url: 'https://news.google.com/rss/search?q=Indian+expats+GCC&hl=en-IN&gl=IN&ceid=IN:en', name: 'Google News - India GCC', category: 'gcc', region: 'gcc' },
  { url: 'https://news.google.com/rss/search?q=Kerala+news&hl=en-IN&gl=IN&ceid=IN:en', name: 'Google News - Kerala', category: 'india', region: 'kerala' },
  { url: 'https://news.google.com/rss/search?q=Dubai+India+business&hl=en&gl=AE&ceid=AE:en', name: 'Google News - Dubai India', category: 'business', region: 'gcc' },
];

export const YOUTUBE_CHANNELS = [
  { channelId: 'UCZFMRhFE8wT_a3dWG6jA-w', name: 'NDTV', category: 'india' },
  { channelId: 'UCn_sFHSIJuezVFRIVoGzfAg', name: 'Asianet News', category: 'india' },
  { channelId: 'UCP0uG-mcMImgKnJz-VjVZkQ', name: 'Manorama News', category: 'india' },
  { channelId: 'UC4GNaC2DXBHY8tGikK3bqIw', name: 'Gulf News', category: 'gcc' },
  { channelId: 'UCNye-wNBqNL5ZzHSJj3l8Bg', name: 'Al Jazeera English', category: 'gcc' },
  { channelId: 'UC7fWeaHhqgM4Lba7wehMhKw', name: 'TRT World', category: 'gcc' },
  { channelId: 'UC_gUM8rL-Lrg6O3adPW9K1g', name: 'WION', category: 'india' },
  { channelId: 'UCwouKE4bKDRetlX0YRFYkCQ', name: 'Republic TV', category: 'india' },
];

export const CATEGORIES = [
  { id: 'all', name: 'All News', color: 'bg-gray-100 text-gray-700' },
  { id: 'breaking', name: 'Breaking', color: 'bg-red-100 text-red-700' },
  { id: 'india', name: 'India', color: 'bg-orange-100 text-orange-700' },
  { id: 'gcc', name: 'GCC', color: 'bg-green-100 text-green-700' },
  { id: 'business', name: 'Business', color: 'bg-blue-100 text-blue-700' },
  { id: 'technology', name: 'Technology', color: 'bg-purple-100 text-purple-700' },
  { id: 'sports', name: 'Sports', color: 'bg-yellow-100 text-yellow-700' },
  { id: 'entertainment', name: 'Entertainment', color: 'bg-pink-100 text-pink-700' },
  { id: 'health', name: 'Health', color: 'bg-emerald-100 text-emerald-700' },
];
